#! /bin/sh

export QT_QPA_PLATFORMTHEME="qt5ct"
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四

bspc config border_width         0
bspc config window_gap           0

bspc config focused_border_color "#FF5370"
bspc config focus_follows_pointer false

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostart
picom -b &
sxhkd &
nitrogen --restore &
polybar &
xfce4-power-manager &
dunst &
solaar &
