#! /bin/sh

xrandr --output DP-0 --primary --mode 2560x1440 --rate 180 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --left-of DP-0
export QT_QPA_PLATFORMTHEME="qt5ct"
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -s HDMI-0
bspc monitor DP-0 -d 一 二 三 四
bspc monitor HDMI-0 -d 五 六 七 八

bspc config border_width         2
bspc config window_gap           2

bspc config pointer_motion_interval 5ms

bspc config focused_border_color "#FF5370"
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostart
picom -b &
sxhkd &
nitrogen --restore &
polybar example &
polybar external &
xfce4-power-manager &
dunst &
solaar &
